version: '3.1'

services:
  mlchallenge:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - dbpostgres
    networks:
      - postgres-network
  dbpostgres:
    image: postgres
    container_name: dbpostgres
    environment:
      POSTGRES_DB: mercadolibre_challenge
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Postgres2020!"
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - postgres-network
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "leo@leo.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2020!"
    ports:
      - "81:80"
    depends_on:
      - dbpostgres
    networks:
      - postgres-network
networks: 
  postgres-network:
    driver: bridge
volumes:
      pg-data:
        driver: local